/**
 * @brief MAC Master TX Transaction.
 *
 * Represents a single transmit transaction generated by the
 * master TX agent. This sequence item contains all fields
 * required to create and transfer a MAC frame between the
 * sequence, driver, and monitor.
 */
class mac_tx_item_c extends uvm_sequence_item;
  `uvm_object_utils(mac_tx_item_c)

  extern function new(string name = "mac_tx_item_c");
endclass

/**
 * @brief Constructor for the MAC Master TX transaction.
 *
 * Initializes the transaction object by calling the parent
 * class constructor.
 *
 * @param name Name of the transaction object.
 */
function mac_tx_item_c::new(string name = "mac_tx_item_c");
  super.new(name);
endfunction
