/**
 * @brief MAC Master TX Transaction.
 *
 * Represents a single transmit transaction generated by the
 * master TX agent. This sequence item contains all fields
 * required to create and transfer a MAC frame between the
 * sequence, driver, and monitor.
 */
class mac_wr_xtn_c extends uvm_sequence_item;
  `uvm_object_utils(mac_wr_xtn_c)

  extern function new(
    string name = "mac_wr_xtn_c"
  );
endclass

/**
 * @brief Constructor for the MAC Master TX transaction.
 *
 * Initializes the transaction object by calling the parent
 * class constructor.
 *
 * @param name Name of the transaction object.
 */
function mac_wr_xtn_c::new(
  string name = "mac_wr_xtn_c"
);
  super.new(name);
endfunction
